using Lofn.DTO.Category;
using Lofn.DTO.Product;
using Lofn.DTO.ShopCart;
using Lofn.DTO.Store;

namespace Lofn.ApiTests.Helpers
{
    public static class TestDataHelper
    {
        public static CategoryInsertInfo CreateCategoryInsertInfo(string? name = null, long? parentCategoryId = null) =>
            new CategoryInsertInfo
            {
                Name = name ?? $"Test Category {Guid.NewGuid():N}",
                ParentCategoryId = parentCategoryId
            };

        public static CategoryUpdateInfo CreateCategoryUpdateInfo(long categoryId = 1, string? name = null, long? parentCategoryId = null) =>
            new CategoryUpdateInfo
            {
                CategoryId = categoryId,
                Name = name ?? $"Updated Category {Guid.NewGuid():N}",
                ParentCategoryId = parentCategoryId
            };

        public static CategoryGlobalInsertInfo CreateCategoryGlobalInsertInfo(string? name = null, long? parentCategoryId = null) =>
            new CategoryGlobalInsertInfo
            {
                Name = name ?? $"Test Global Category {Guid.NewGuid():N}",
                ParentCategoryId = parentCategoryId
            };

        public static CategoryGlobalUpdateInfo CreateCategoryGlobalUpdateInfo(long categoryId = 1, string? name = null, long? parentCategoryId = null) =>
            new CategoryGlobalUpdateInfo
            {
                CategoryId = categoryId,
                Name = name ?? $"Updated Global Category {Guid.NewGuid():N}",
                ParentCategoryId = parentCategoryId
            };

        public static ProductInsertInfo CreateProductInsertInfo(string? name = null) =>
            new ProductInsertInfo
            {
                Name = name ?? $"Test Product {Guid.NewGuid():N}",
                Description = "Generated by Lofn.ApiTests",
                Price = 99.90,
                Discount = 0,
                Frequency = 0,
                Limit = 0,
                Status = ProductStatusEnum.Active,
                ProductType = ProductTypeEnum.Physical,
                Featured = false
            };

        public static ProductUpdateInfo CreateProductUpdateInfo(long productId = 1, string? name = null) =>
            new ProductUpdateInfo
            {
                ProductId = productId,
                Name = name ?? $"Updated Product {Guid.NewGuid():N}",
                Description = "Updated by Lofn.ApiTests",
                Price = 149.90,
                Discount = 10,
                Frequency = 0,
                Limit = 0,
                Status = ProductStatusEnum.Active,
                ProductType = ProductTypeEnum.Physical,
                Featured = false
            };

        public static ProductSearchParam CreateProductSearchParam() =>
            new ProductSearchParam
            {
                Keyword = string.Empty,
                OnlyActive = true,
                PageNum = 1
            };

        public static ShopCartInfo CreateShopCartInfo() =>
            new ShopCartInfo
            {
                User = new NAuth.DTO.User.UserInfo
                {
                    UserId = 1,
                    Email = "shopcart@example.com",
                    Name = "Test ShopCart User"
                },
                Address = new ShopCartAddressInfo
                {
                    ZipCode = "01310-100",
                    Address = "Av. Paulista, 1000",
                    Complement = "Apto 1",
                    Neighborhood = "Bela Vista",
                    City = "São Paulo",
                    State = "SP"
                },
                Items = new List<ShopCartItemInfo>
                {
                    new ShopCartItemInfo
                    {
                        Product = new ProductInfo
                        {
                            ProductId = 1,
                            Name = "Sample Product",
                            Price = 99.90
                        },
                        Quantity = 1
                    }
                },
                CreatedAt = DateTime.UtcNow
            };

        public static StoreInsertInfo CreateStoreInsertInfo(string? name = null) =>
            new StoreInsertInfo
            {
                Name = name ?? $"Test Store {Guid.NewGuid():N}"
            };

        public static StoreUpdateInfo CreateStoreUpdateInfo(long storeId = 1, string? name = null) =>
            new StoreUpdateInfo
            {
                StoreId = storeId,
                Name = name ?? $"Updated Store {Guid.NewGuid():N}",
                Status = StoreStatusEnum.Active
            };

        public static StoreUserInsertInfo CreateStoreUserInsertInfo(long userId = 1) =>
            new StoreUserInsertInfo
            {
                UserId = userId
            };

        public static byte[] CreateMinimalPngBytes() => new byte[]
        {
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A,
            0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
            0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
            0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4,
            0x89, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x44, 0x41,
            0x54, 0x78, 0x9C, 0x62, 0x00, 0x01, 0x00, 0x00,
            0x05, 0x00, 0x01, 0x0D, 0x0A, 0x2D, 0xB4, 0x00,
            0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE,
            0x42, 0x60, 0x82
        };
    }
}
